services:
  - type: web
    name: student-performance-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:app
    envVars:
      - key: FLASK_ENV
        value: production
